version: '3'
services:
  squid-proxy:
    build:
      context: .
      args:
        - SQUID_VERSION=5.6
    image: goonnowgit/squid:5.6
    ports:
      - 3128:3128
    cap_drop:
    - audit_write
    - setfcap
    - setpcap
    - fowner
    - mknod
    - sys_chroot
    volumes:
      - ./confs:/etc/squid
      - ./acls:/etc/squid/acls
      - ./ssl_cert:/etc/squid/ssl_cert
      - ./cache:/var/spool/squid
      - ./ssl_db:/var/lib
      - ./logs:/var/log/squid
      - ./run:/var/run
    restart: unless-stopped
