name: Sandbox dnscrypt-proxy workflow

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker-compose build
